### PR TITLE
46

### LINKED ISSUE #46: CSS: Forms
Style all forms:
- sign up
- sign in
- sign out
- create space
- book place
- confirm/decline booking

### PR DESCRIPTION
**Pull request by anne-lydon**
close #46

### CODE REVIEW

**Comment by kylebuttner** [comment]
Good stuff lets :shipit:

**Comment by kylebuttner** [comment]
jk let's run rspec first

**Comment by kylebuttner** [comment]
Ok now we can :shipit:

**Comment by robota-x** [comment]
:shipit:

**Pull request merged**
